import React, { useState, useEffect } from 'react';
import { AppState, Language, MathResponse, AISettings, DEFAULT_SETTINGS } from './types';
import { solveMathProblem, fileToBase64 } from './services/geminiService';
import { ImageInput } from './components/ImageInput';
import { SolutionView } from './components/SolutionView';
import { SettingsModal } from './components/SettingsModal';
import { Icons } from './components/Icon';

const TRANSLATIONS = {
  en: {
    title: "MathSnap",
    heroTitle: "Master Math in a Snap",
    heroDesc: "Stuck on a problem? Take a photo and let our AI tutor explain the solution step-by-step.",
    analyzingTitle: "Analyzing image...",
    thinkingTitle: "Thinking...",
    timeEst: "This typically takes 5-10 seconds",
    errorTitle: "Oops!",
    errorGeneric: "Something went wrong. Please try again.",
    tryAgain: "Try Again",
    backToCamera: "Back to Camera",
    generatedBy: "Generated by",
    footer: "MathSnap. Built for students.",
    settings: "Settings",
    loadingMessages: [
      "Identifying problem...",
      "Understanding concepts...",
      "Calculations in progress...",
      "Formulating explanation...",
      "Creating practice quiz...",
      "Double-checking math..."
    ]
  },
  zh: {
    title: "数学拍 (MathSnap)",
    heroTitle: "轻松掌握数学",
    heroDesc: "遇到难题了吗？拍张照片，让人工智能导师为您详细讲解解题步骤。",
    analyzingTitle: "正在分析图片...",
    thinkingTitle: "思考中...",
    timeEst: "通常需要 5-10 秒",
    errorTitle: "哎呀！",
    errorGeneric: "出错了，请重试。",
    tryAgain: "重试",
    backToCamera: "返回相机",
    generatedBy: "生成模型：",
    footer: "MathSnap. 专为学生打造。",
    settings: "设置",
    loadingMessages: [
      "正在识别题目...",
      "正在理解概念...",
      "正在计算...",
      "正在组织讲解...",
      "正在生成互动测验...",
      "正在复查结果..."
    ]
  }
};

export default function App() {
  const [appState, setAppState] = useState<AppState>(AppState.IDLE);
  const [language, setLanguage] = useState<Language>('zh');
  const [currentImage, setCurrentImage] = useState<string | null>(null);
  
  // Update state to hold the MathResponse object
  const [response, setResponse] = useState<MathResponse | null>(null);
  const [error, setError] = useState<string | null>(null);
  
  // Settings State
  const [showSettings, setShowSettings] = useState(false);
  
  // Lazy initialization for persistent settings
  const [aiSettings, setAiSettings] = useState<AISettings>(() => {
    try {
      const saved = localStorage.getItem('mathsnap_settings');
      if (saved) {
        const parsed = JSON.parse(saved);
        // Deep merge to ensure structure integrity
        const merged = { 
          ...DEFAULT_SETTINGS, 
          ...parsed,
          keys: { ...DEFAULT_SETTINGS.keys, ...(parsed.keys || {}) }
        };
        
        // If Gemini key is empty in storage but present in Env, use Env
        if (!merged.keys.gemini && process.env.API_KEY) {
           merged.keys.gemini = process.env.API_KEY;
        }
        return merged;
      }
    } catch (e) {
      console.error("Failed to load settings from local storage", e);
    }
    
    // Default fallback with Env key
    const defaults = { ...DEFAULT_SETTINGS };
    if (process.env.API_KEY) {
      defaults.keys.gemini = process.env.API_KEY;
    }
    return defaults;
  });

  const t = TRANSLATIONS[language];
  const [loadingText, setLoadingText] = useState(t.analyzingTitle);

  useEffect(() => {
    setLoadingText(t.analyzingTitle);
  }, [language, appState, t.analyzingTitle]);

  useEffect(() => {
    let interval: ReturnType<typeof setInterval>;
    if (appState === AppState.ANALYZING) {
      const messages = t.loadingMessages;
      let i = 0;
      interval = setInterval(() => {
        setLoadingText(messages[i % messages.length]);
        i++;
      }, 1500);
    }
    return () => {
      if (interval) clearInterval(interval);
    };
  }, [appState, language, t.loadingMessages]);

  const handleSettingsSave = (newSettings: AISettings) => {
    setAiSettings(newSettings);
    localStorage.setItem('mathsnap_settings', JSON.stringify(newSettings));
  };

  const handleImageSelect = async (file: File) => {
    // Check if key exists for current provider
    const currentKey = aiSettings.keys[aiSettings.provider];
    
    // If we are using Gemini and have a process.env fallback, that's okay, otherwise check user key
    const hasEnvKey = aiSettings.provider === 'gemini' && process.env.API_KEY;

    if (!currentKey && !hasEnvKey) {
        setShowSettings(true);
        setError(language === 'zh' ? "请先在设置中配置 API Key。" : "Please configure your API Key in Settings first.");
        return;
    }

    try {
      setAppState(AppState.ANALYZING);
      setError(null);
      setResponse(null); // Clear previous response
      
      const base64 = await fileToBase64(file);
      setCurrentImage(base64);

      // Pass the mime type (e.g., 'image/png') to the solver to avoid API 400 errors
      const result = await solveMathProblem(base64, file.type || 'image/jpeg', language, aiSettings);
      setResponse(result);
      setAppState(AppState.SUCCESS);

    } catch (err: any) {
      console.error(err);
      setError(err.message || t.errorGeneric);
      setAppState(AppState.ERROR);
    }
  };

  const handleReset = () => {
    setAppState(AppState.IDLE);
    setCurrentImage(null);
    setResponse(null);
    setError(null);
  };

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'zh' : 'en');
  };

  return (
    <div className="min-h-screen bg-slate-50 flex flex-col font-sans">
      
      <SettingsModal 
        isOpen={showSettings} 
        onClose={() => setShowSettings(false)} 
        settings={aiSettings}
        onSave={handleSettingsSave}
        lang={language}
      />

      {/* Header */}
      <header className="bg-white border-b border-slate-200 sticky top-0 z-50 safe-top">
        <div className="max-w-5xl mx-auto px-4 h-16 flex items-center justify-between">
          <div className="flex items-center space-x-2 cursor-pointer min-w-0" onClick={handleReset}>
            <div className="bg-indigo-600 p-1.5 rounded-lg flex-shrink-0">
               <span className="text-white font-bold text-xl leading-none">∑</span>
            </div>
            <h1 className="text-lg md:text-xl font-bold bg-gradient-to-r from-indigo-600 to-purple-600 bg-clip-text text-transparent truncate">
              {t.title}
            </h1>
          </div>
          
          <div className="flex items-center space-x-2 flex-shrink-0 ml-2">
             <button 
               onClick={toggleLanguage}
               className="flex items-center px-3 py-1.5 rounded-full bg-slate-100 hover:bg-slate-200 text-slate-700 font-semibold text-sm transition-colors border border-slate-200"
             >
               <span className={language === 'zh' ? "text-indigo-600" : "text-slate-400"}>中</span>
               <span className="mx-1 text-slate-300">/</span>
               <span className={language === 'en' ? "text-indigo-600" : "text-slate-400"}>EN</span>
             </button>
             
             <button
               onClick={() => setShowSettings(true)}
               className="p-2 rounded-full bg-slate-100 hover:bg-indigo-50 text-slate-600 hover:text-indigo-600 transition-colors border border-slate-200"
               aria-label={t.settings}
             >
                <Icons.Settings className="w-5 h-5" />
             </button>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="flex-1 w-full max-w-5xl mx-auto px-4 py-8 flex flex-col items-center justify-center">
        
        {/* State: IDLE */}
        {appState === AppState.IDLE && (
          <div className="w-full flex flex-col items-center animate-fade-in">
            <div className="text-center mb-10 max-w-lg">
              <h2 className="text-3xl md:text-4xl font-extrabold text-slate-900 mb-4 tracking-tight">
                {t.heroTitle}
              </h2>
              <p className="text-lg text-slate-500 mb-2">
                {t.heroDesc}
              </p>
              <div className="flex items-center justify-center space-x-2 text-xs text-slate-400">
                <span>{t.generatedBy} {aiSettings.model}</span>
              </div>
            </div>
            <ImageInput onImageSelected={handleImageSelect} isProcessing={false} lang={language} />
          </div>
        )}

        {/* State: ANALYZING */}
        {appState === AppState.ANALYZING && (
          <div className="w-full flex flex-col items-center justify-center py-12 animate-fade-in">
            <div className="relative w-64 h-64 md:w-80 md:h-80 mb-8 rounded-2xl overflow-hidden shadow-2xl border-4 border-white">
              {currentImage && (
                <img 
                  src={`data:image/jpeg;base64,${currentImage}`} 
                  alt="Analyzing" 
                  className="w-full h-full object-cover opacity-80"
                />
              )}
              <div className="absolute inset-0 bg-indigo-900/30 backdrop-blur-sm flex flex-col items-center justify-center">
                <Icons.Spinner className="w-16 h-16 text-white animate-spin mb-4" />
                <span className="text-white font-medium text-lg tracking-wide drop-shadow-md">
                  {t.thinkingTitle}
                </span>
              </div>
            </div>
            <h3 className="text-xl font-semibold text-slate-700 animate-pulse text-center px-4">
              {loadingText}
            </h3>
            <p className="text-slate-400 mt-2 text-sm">{t.timeEst}</p>
          </div>
        )}

        {/* State: ERROR */}
        {appState === AppState.ERROR && (
          <div className="w-full max-w-md bg-white p-8 rounded-2xl shadow-xl text-center animate-fade-in">
            <div className="w-16 h-16 bg-red-100 rounded-full flex items-center justify-center mx-auto mb-4 text-red-600">
              <Icons.Alert className="w-8 h-8" />
            </div>
            <h3 className="text-xl font-bold text-slate-800 mb-2">{t.errorTitle}</h3>
            <p className="text-slate-600 mb-6 break-words">
              {error}
            </p>
            <div className="space-y-3">
              <button
                onClick={handleReset}
                className="w-full bg-slate-900 hover:bg-slate-800 text-white font-medium py-3 px-4 rounded-xl transition-colors"
              >
                {t.tryAgain}
              </button>
              <button
                onClick={() => setShowSettings(true)}
                className="w-full bg-white border border-slate-300 hover:bg-slate-50 text-slate-700 font-medium py-3 px-4 rounded-xl transition-colors"
              >
                {t.settings}
              </button>
            </div>
          </div>
        )}

        {/* State: SUCCESS */}
        {appState === AppState.SUCCESS && response && (
          <div className="w-full animate-fade-in">
            <div className="mb-6 flex justify-center">
               <div className="w-full max-w-3xl flex items-center justify-between mb-4 px-2">
                 <button 
                   onClick={handleReset}
                   className="flex items-center text-slate-500 hover:text-indigo-600 transition-colors text-sm font-medium"
                 >
                   <Icons.Back className="w-4 h-4 mr-1" />
                   {t.backToCamera}
                 </button>
                 <span className="text-xs font-mono text-slate-400 bg-slate-100 px-2 py-1 rounded">
                   {t.generatedBy} {aiSettings.model}
                 </span>
               </div>
            </div>
            {/* Pass the full response object to SolutionView */}
            <SolutionView response={response} onReset={handleReset} lang={language} />
          </div>
        )}
      </main>

      {/* Footer */}
      <footer className="py-6 text-center text-slate-400 text-sm">
        <p>&copy; {new Date().getFullYear()} {t.footer}</p>
      </footer>
    </div>
  );
}